### ISSUE TITLE
Error for executing 05 local execution notebook 

### ISSUE THREAD

**Issue by cyc00518** [aurelio-labs/semantic-router#138]
Hi, 
Thanks for create quite good package!

When I try to add llm in RouteLayer, I will face some output error.
And this error will happen nomatter close/open model I choose.

For example:
I follow all the 05 local execution notebook step by step,but when I ask some query may use function call, there will be this error
![image](https://github.com/aurelio-labs/semantic-router/assets/96753147/573eb588-99c6-44cd-9e7f-4e307dfe4c2f)
![image](https://github.com/aurelio-labs/semantic-router/assets/96753147/fa32ee61-1b7a-4f93-9815-df10ca02d8f7)
![image](https://github.com/aurelio-labs/semantic-router/assets/96753147/3b1c3b78-9d12-4f7a-9c28-a4d459780b48)
![image](https://github.com/aurelio-labs/semantic-router/assets/96753147/2febc170-e9f3-47e4-bd75-d569082883ad)

Thanks for your kindly help!

**Comment by pomadomaphin** [comment]
I also have this issue

**Comment by cyc00518** [comment]
@pomadomaphin 
Thanks for your kindly reply.
I found why I get this error.
I build this project in docker but I set semantic-router[local] in requierement.txt.
So it will install a version of Torch that is not compatible with my Docker image.

**Comment by Siraj-Aizlewood** [comment]
Hi @cyc00518,

I've taken a look into this. Here are my findings:

1. I tried getting it working with GPU acceleration on my Windows OS (with an Nvidia GPU), and ran into issues with getting CUDA to work together with llama.cpp. I kept getting the same `No output generated` exception that you get. For Windows at least, it seems pretty tricky to get everything working together. [This](https://www.reddit.com/r/LocalLLaMA/comments/152kn39/current_comprehensive_guide_to_to_installing/) Reddit thread hints that a prerequistie is to install relevant extensions in Visual Studio and ensuring that integrate properly with the CUDA installation. Then there is a suggestion to recompile llama-cpp-python manually using Visual Studio. That all said, I'd try @pomadomaphin suggestion first to see if that works. 
2. However, I think there's a second issue at play here also: I tried running the code on Google Colab (Linux) to see if it works on a different OS, and got the same error message again, using both CPU and GPU. I tried simplifying the user input and arguments sent to the LLM to see if it was an issue with the arguments that we provide, and that didn't change the outcome. I believe there could be a second problem, as outlined in these Llama.cpp issues:
  - https://github.com/ggerganov/llama.cpp/issues/2460
  - https://github.com/ggerganov/llama.cpp/issues/2474
 The fix is relatively simple, just change:
 ` std::discrete_distribution<> dist(probs.begin(), probs.end());`
 to:
 'std::discrete_distribution<> dist(*probs.begin(), *probs.end());'
 in the `llama.cpp` file, in a fork of the Llama.cpp project. 
 However, it's C++, so to get it working as Python package, it needs to be compiled/built and Python bindings need to be added.
 
I don't think this is an issue with the Semantic Router itself, but please let me know if you disagree.

**Comment by ChrisPrice11** [comment]
I ran into this same issue.  Fought for hours trying to get it to run on my M1...decided to try running the code on Google Colab to see if I could find a clue that might lead to where the issue is on my machine.  I received the same error so knew it wasn't just my machine/local setup.  

It's not really a long term fix, but installing version 0.2.28 of llama-cpp-python using the command @pomadomaphin provided in a previous comment at least got the app running enough to continue with local experimentation of semantic-router.
