### ISSUE TITLE
Significance of score_threshold

### ISSUE THREAD

**Issue by AtulyaAgg** [aurelio-labs/semantic-router#140]
What is the significance of score_threshold and how can we set it dynamically?

**Comment by Siraj-Aizlewood** [comment]
Hi @AtulyaAgg,

I'd like to help answer your question. Here's how the `score_threshold` is used:

1. When we add `Routes` to the `RouteLayer`, the utterances associated with them are tokenized and added to the `index` (embedded in the vector database) associated with the `RouteLayer`. This is done for a number of Routes, and the result is a numerous utterances embedded in the vector space, each associated with a unique `Route`.
2. To see which `Route` a new utterance belongs to (via `RouteLayer.__call__()`) we tokenize and embed that new utterance, and determine its pair-wise cosine similarity with the `Route`s utterances embeddings. Then we keep track of those Route embeddings with cosine similarity in the `top_k` (default value 5) of all cosine similarities. See `RouterLayer._retrieve`.

3. Now suppose the new utterance "I'd like a freebie please" (with regards to offers from some retailer) gives the following highest cosine similarities:


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Siraj/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Siraj/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Route   Utterance # | Corresponding   Route Name | Cosine   Similarity with New Utterance
-- | -- | --
"I'd like   to buy x" | Sales | 0.3
"How much   does x cost?" | Sales | 0.1
"Do you   sell x?" | Sales | 0.2
"Can I   have a freebie?" | Promotions and Offers | 0.65
"I'd like   a discount please!" | Promotions and Offers | 0.9



</body>

</html>

4. In `RouterLayer._semantic_classify`, you'll see that we group by `Route` and sum the scores, giving:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Siraj/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Siraj/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Corresponding   Route Name | Total Score
-- | --
Sales | 0.6
Promotions and   Offers | 1.55



</body>

</html>

The `top_class` is the one with the highest score. In this case "Promotions and Offers". 

5. Finally, the `score_threshold` comes into play: This is a `Route` level parameter, and we use it in `RouteLayer._pass_threshold()'. In this method, we take the maximum cosine similarity that is associated with the `top_class`. In this case, the `top_class` is "Promotions and Offers" and the maximum cosine similarity it has is 0.9. 

If the `score_threshold` is set to something lower than 0.9, then the similarity to the "Promotions and Offers" utturances is strong enough that we decide the new utterance - "I'd like a freebie please" - does indeed belong to this class/`Route`.

If `score_threshold` is greater than or equal to 0.9, then we don't classify the new utterance as "Promotions and Offers", instead we essentially classify it as "Other": We decide that none of the `Routes` contain utterances similar enough to "I'd like a freebie please", and the Semantic Router essentially ignores it. If you were using the Semantic Router with a chatbot, the upshot is that none of the `Routes` would be triggered, and the LLM would just respond as normal to "I'd like a freebie please".

So, the threshold essential determines whether we should classify an utterance under the top `Route`, or not apply a `Route` to it at all.



You mentioned setting the threshold for the `Routes` dynamically. There are a few points to mention here:

- Each `Route` has a `score_threshold` attribute. So, you can set this when defining the `Route`:

E.g. 

```
politics = Route(
    name="politics",
    utterances=[
        "isn't politics the best thing ever",
        "why don't you tell me about your political opinions",
        "don't you just love the president" "don't you just hate the president",
        "they're going to destroy this country!",
        "they will save the country!",
    ],
    score=0.5,
)
```

- If you don't explicitly specify a `score_threshold` for a Route, when you add it to the `RouteLayer`, the default `RouteLayer` `score_threshold` is used instead, and this is determined by the chosen `encoder` associated with that `RouteLayer` object. This is because we found that different encoders have different optimum thresholds.

- We recommend using the `RouteLayer.fit()` method to optimise/fine-tune thresholds to your specific `Routes` and their associated utterances. You can see how to do this in `06-threshold-optimization.ipynb`. You should see significantly improved performance by doing this.


I hope that helps, please let me know if you have any other questions.

**Comment by Siraj-Aizlewood** [comment]
I'll close this shortly unless there are any further questions.

**Comment by AtulyaAgg** [comment]
sure @Siraj-Aizlewood thank you so much

**Comment by Siraj-Aizlewood** [comment]
You're welcome :-)
